let a = +prompt();
let b = +prompt();
let c = +prompt();
let d = +prompt();
let e = +prompt();
(isNaN(a) == false && a % 2 === 0) ? (console.log(`${a}-чет`)) : (console.log(`${a}-неч`));
(isNaN(b) == false && b % 2 === 0) ? (console.log(`${b}-чет`)) : (console.log(`${b}-неч`));
(isNaN(c) == false && c % 2 === 0) ? (console.log(`${c}-чет`)) : (console.log(`${c}-неч`));
(isNaN(d) == false && d % 2 === 0) ? (console.log(`${d}-чет`)) : (console.log(`${d}-неч`));
(isNaN(e) == false && e % 2 === 0) ? (console.log(`${e}-чет`)) : (console.log(`${e}-неч`));